AdvertizingAgency1/Controllers/RazrabotkiController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdvertizingAgency1.Models;
using BusinessLogic;
using DAL;

namespace AdvertizingAgency1.Controllers
{
    public class RazrabotkiController : Controller
    {
        private DataManager dataManager;

        public RazrabotkiController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
         [Authorize(Roles = "admin,designer")]
        //загрузка файлов макета
        [HttpGet]
        public ActionResult AddFileMakets(int id)
        {
            ViewBag.Dogovor = id;
            return View(id);
        }
         [Authorize(Roles = "admin,designer")]
        [HttpPost]
        public ActionResult AddFileMakets(IEnumerable<HttpPostedFileBase> fileUpload, string id)
        {
            string dogovor = id;
            string domainpath = Server.MapPath("~/UploadFiles/Makets/" + dogovor);
            if (!Directory.Exists(domainpath))
                Directory.CreateDirectory(domainpath); // Создаем директорию, если нужно
            Разработки existRazrab = dataManager.RazrabotkiRepository.GetRazrabotkiById(int.Parse(id));
            if (existRazrab != null)
            {
                dataManager.RazrabotkiRepository.ChangeRazrabotki(int.Parse(id), domainpath, existRazrab.Оригинал , existRazrab.Отчёт);
            }
            else
            {
                dataManager.RazrabotkiRepository.CreateRazrabotki(int.Parse(id), domainpath, "нет", "нет");
            }
        
            foreach (var file in fileUpload)
            {
                if (file!= null && file.ContentLength>0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(domainpath, fileName);
                    file.SaveAs(path);
                }
            }     
            return RedirectToAction("SDesigner","Dogovora");
        }
//загрузка файлов оригинала

         [Authorize(Roles = "admin,designer")]
        [HttpGet]
        public ActionResult AddFileOriginal(int id)
        {
            ViewBag.Dogovor = id;
            return View(id);
        }
         [Authorize(Roles = "admin,designer")]
        [HttpPost]
        public ActionResult AddFileOriginal(IEnumerable<HttpPostedFileBase> fileUpload, string id)
        {
            string dogovor = id;
            string domainpath = Server.MapPath("~/UploadFiles/Original/" + dogovor);
            if (!Directory.Exists(domainpath))
                Directory.CreateDirectory(domainpath); // Создаем директорию, если нужно


            Разработки existRazrab = dataManager.RazrabotkiRepository.GetRazrabotkiById(int.Parse(id));
            if (existRazrab != null)
            {
                dataManager.RazrabotkiRepository.ChangeRazrabotki(int.Parse(id), existRazrab.Макет, domainpath, existRazrab.Отчёт);
            }
            else
            {
                dataManager.RazrabotkiRepository.CreateRazrabotki(int.Parse(id), "нет", domainpath, "нет");
            }
          
            foreach (var file in fileUpload)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(domainpath, fileName);
                    file.SaveAs(path);
                }
            }
            return RedirectToAction("SMakeOriginal", "Dogovora");
        }

        //загрузка файлов отчёта установки

         [Authorize(Roles = "admin,installer")]
        [HttpGet]
        public ActionResult AddFileOtchets(int id)
        {
            ViewBag.Dogovor = id;
            return View(id);
        }
         [Authorize(Roles = "admin,installer")]
        [HttpPost]
        public ActionResult AddFileOtchets(IEnumerable<HttpPostedFileBase> fileUpload, string id)
        {
            string dogovor = id;
            string domainpath = Server.MapPath("~/UploadFiles/Otchets/" + dogovor);
            if (!Directory.Exists(domainpath))
                Directory.CreateDirectory(domainpath); // Создаем директорию, если нужно

            Разработки existRazrab = dataManager.RazrabotkiRepository.GetRazrabotkiById(int.Parse(id));
            if(existRazrab!=null)
            {
                dataManager.RazrabotkiRepository.ChangeRazrabotki(int.Parse(id), existRazrab.Макет,existRazrab.Оригинал , domainpath);
            }
            else
            {
                dataManager.RazrabotkiRepository.CreateRazrabotki(int.Parse(id),"нет","нет",domainpath);
            }
           
            foreach (var file in fileUpload)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(domainpath, fileName);
                    file.SaveAs(path);
                }
            }
            return RedirectToAction("SRedyForSets", "Dogovora");
        }
         [Authorize(Roles = "admin,maneger")]
        //скачиваем файлы  макета на компьютер с сервера
        [HttpGet]
        public ActionResult DownloadsMakets(int id)
        {
            ViewBag.Dogovor = id;
            DownloadFilesViewModel model = new DownloadFilesViewModel();
            model.NumberOfDogovor = id;
            if(dataManager.RazrabotkiRepository.GetRazrabotkiById(id)!=null &&dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Макет!="нет")
            { 
                var dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Макет);
           
                 FileInfo[] fileNames = dir.GetFiles("*.*");
                 List<string> item = new List<string>();
                if(fileNames.Any())
                { 
                    foreach (var file in fileNames)
                    {
                       item.Add(file.Name);
                    }
                    model.FileList = item;
                    return View(model);
                }
                else
                {
                    return RedirectToAction("EmptyFiles");
                }
            }
            return RedirectToAction("EmptyFiles");
        }
        //сохранение файла
        public FileResult Download(string ImageName, int id)
        {
         
            DirectoryInfo dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Макет+"//");
        
            string contentType = "application/jpg";
            return File(dir + ImageName, contentType, id.ToString()+"Макет.jpg");
        } 
        //страница если нет файлов
        public ActionResult EmptyFiles()
        {
            return View();
        }
         [Authorize(Roles = "admin,master")]
        //скачиваем файлы оригиналов на компьютер с сервера
        [HttpGet]
        public ActionResult DownloadsOriginal(int id)
        {
            ViewBag.Dogovor = id;
            DownloadFilesViewModel model = new DownloadFilesViewModel();
            model.NumberOfDogovor = id;
            if(dataManager.RazrabotkiRepository.GetRazrabotkiById(id)!=null && dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Оригинал!="нет")
            { 
                var dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Оригинал);
          
                FileInfo[] fileNames = dir.GetFiles("*.*");
                List<string> item = new List<string>();
                if (fileNames.Any())
                {
                    foreach (var file in fileNames)
                    {
                        item.Add(file.Name);
                    }
                    model.FileList = item;
                    return View(model);
                }
                else
                {
                    return RedirectToAction("EmptyFilesOriginal");
                }
            }
            return RedirectToAction("EmptyFilesOriginal");
        }
        //сохранение файла
        public FileResult DownloadOriginal(string ImageName, int id)
        {

            DirectoryInfo dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Оригинал + "//");

            string contentType = "application/jpg";
            return File(dir + ImageName, contentType, id.ToString() + "Оригинал.jpg");
        }
        //страница если нет файлов

        public ActionResult EmptyFilesOriginal()
        {
            return View();
        }
         [Authorize(Roles = "admin,maneger")]
        //скачиваем файлы отчёты на компьютер с сервера
        [HttpGet]
        public ActionResult DownloadsOtchet(int id)
        {
            ViewBag.Dogovor = id;
            DownloadFilesViewModel model = new DownloadFilesViewModel();
            model.NumberOfDogovor = id;
            if (dataManager.RazrabotkiRepository.GetRazrabotkiById(id) != null && dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Отчёт!="нет")
            { 
            var dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Отчёт);

            FileInfo[] fileNames = dir.GetFiles("*.*");
            List<string> item = new List<string>();
            if (fileNames.Any())
            {
                foreach (var file in fileNames)
                {
                    item.Add(file.Name);
                }
                model.FileList = item;
                return View(model);
            }
            else
            {
                return RedirectToAction("EmptyFilesOtchet");
            }
            }
            return RedirectToAction("EmptyFilesOtchet");
        }
        //сохранение файла
        public FileResult DownloadOtchet(string ImageName, int id)
        {

            DirectoryInfo dir = new DirectoryInfo(dataManager.RazrabotkiRepository.GetRazrabotkiById(id).Отчёт + "//");

AdvertizingAgency1/Views/Razrabotki/AddFileMakets.cshtml
@model int
@{
    ViewBag.Title = "Загрузка файлов макета";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Выберите файлы макетов договора №@ViewBag.Dogovor загрузки </h2>
    <div class="formEditOrCreate">
        <p>
            @using (Html.BeginForm("AddFileMakets", "Razrabotki", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset class="fieldsetform">
                    <legend>Выберите файлы для загрузки на сервер</legend>
                    @Html.Hidden(Model.ToString())
                    <br/>
                    <input type="file" name="fileUpload[0]" /><br />
                    <input type="file" name="fileUpload[1]" /><br />
                    <input type="file" name="fileUpload[2]" /><br />
                    <input type="file" name="fileUpload[3]" /><br />
                    <input type="file" name="fileUpload[4]" /><br />
                    <input type="file" name="fileUpload[5]" /><br />
                    <input type="file" name="fileUpload[6]" /><br />
                    <input type="file" name="fileUpload[7]" /><br />
                    <input type="file" name="fileUpload[8]" /><br />
                    <input type="file" name="fileUpload[9]" /><br />
                    <input type="submit" value="Загрузить файлы на сервер" />
                </fieldset>
            }
        </p>
        @Html.ActionLink("Назад", "SDesigner", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/AddFileOriginal.cshtml
@model int
@{
    ViewBag.Title = "Загрузка файлов оригинала";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Выберите файлы оригиналов договора №@ViewBag.Dogovor  для загрузки на сервер</h2>
    <div class="formEditOrCreate">
        <p>
            @using (Html.BeginForm("AddFileOriginal", "Razrabotki", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset class="fieldsetform">
                    <legend>Выберите файлы для загрузки на сервер</legend>
                    @Html.Hidden(Model.ToString())
                    <br />
                    <input type="file" name="fileUpload[0]" /><br />
                    <input type="file" name="fileUpload[1]" /><br />
                    <input type="file" name="fileUpload[2]" /><br />
                    <input type="file" name="fileUpload[3]" /><br />
                    <input type="file" name="fileUpload[4]" /><br />
                    <input type="file" name="fileUpload[5]" /><br />
                    <input type="file" name="fileUpload[6]" /><br />
                    <input type="file" name="fileUpload[7]" /><br />
                    <input type="file" name="fileUpload[8]" /><br />
                    <input type="file" name="fileUpload[9]" /><br />
               
                    <input type="submit" value="Загрузить файлы на сервер" />
                </fieldset>
            }
        </p>
        @Html.ActionLink("Назад", "SMakeOriginal", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/AddFileOtchets.cshtml
@model int
@{
    ViewBag.Title = "Загрузка файлов оригинала";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Выберите файлы отчётов установки договора №@ViewBag.Dogovor  для загрузки на сервер</h2>
    <div class="formEditOrCreate">
        <p>
            @using (Html.BeginForm("AddFileOtchets", "Razrabotki", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset class="fieldsetform">
                    <legend>Выберите файлы для загрузки на сервер</legend>
                    @Html.Hidden(Model.ToString())
                    <br />
                    <input type="file" name="fileUpload[0]" /><br />
                    <input type="file" name="fileUpload[1]" /><br />
                    <input type="file" name="fileUpload[2]" /><br />
                    <input type="file" name="fileUpload[3]" /><br />
                    <input type="file" name="fileUpload[4]" /><br />
                    <input type="file" name="fileUpload[5]" /><br />
                    <input type="file" name="fileUpload[6]" /><br />
                    <input type="file" name="fileUpload[7]" /><br />
                    <input type="file" name="fileUpload[8]" /><br />
                    <input type="file" name="fileUpload[9]" /><br />
              
                    <input type="submit" value="Загрузить файлы на сервер" />
                </fieldset>
            }
        </p>
        @Html.ActionLink("Назад", "SRedyForSets", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/DownloadsMakets.cshtml
@model AdvertizingAgency1.Models.DownloadFilesViewModel
@{
    ViewBag.Title = "Сохранение файлов макетов";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Сохраните файлы макетов договора №@ViewBag.Dogovor</h2>
    <div class="formEditOrCreate">
        <p>
           
            <table class ="tableAny">
                <tr>
                    <th>Имя файла</th> 
                    <th>Ссылка</th> 
                </tr>
                @for (var i = 0; i <= Model.FileList.Count - 1; i++)
                {
                    <tr>
                        @Html.HiddenFor(model => model.NumberOfDogovor)
                        <td> @Model.FileList[i].ToString() </td> 
                        <td> @Html.ActionLink("Сохранить", "Download", new { ImageName = Model.FileList[i].ToString(), id = Model.NumberOfDogovor }) </td> 
                    </tr>
                } 
            </table> 
        </p>
        @Html.ActionLink("Назад", "SLookMaket", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/DownloadsOriginal.cshtml
@model AdvertizingAgency1.Models.DownloadFilesViewModel
@{
    ViewBag.Title = "Сохранение оригинальных файлов разработки";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Сохраните оригиналы файлов разработки договора №@ViewBag.Dogovor</h2>
    <div class="formEditOrCreate">
        <p>

            <table class="tableAny">
                <tr>
                    <th>Имя файла</th>
                    <th>Ссылка</th>
                </tr>
                @for (var i = 0; i <= Model.FileList.Count - 1; i++)
                {
                    <tr>
                        @Html.HiddenFor(model => model.NumberOfDogovor)
                        <td> @Model.FileList[i].ToString() </td>
                        <td> @Html.ActionLink("Сохранить", "DownloadOriginal", new { ImageName = Model.FileList[i].ToString(), id = Model.NumberOfDogovor }) </td>
                    </tr>
                }
            </table>
        </p>
        @Html.ActionLink("Назад", "SInMasters", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/DownloadsOtchet.cshtml
@model AdvertizingAgency1.Models.DownloadFilesViewModel
@{
    ViewBag.Title = "Сохранение отчётных файлов установки";
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
}


<div class="contentformEdit">
    <h2>Сохраните отчёты файлов установки договора №@ViewBag.Dogovor</h2>
    <div class="formEditOrCreate">
        <p>

            <table class="tableAny">
                <tr>
                    <th>Имя файла</th>
                    <th>Ссылка</th>
                </tr>
                @for (var i = 0; i <= Model.FileList.Count - 1; i++)
                {
                    <tr>
                        @Html.HiddenFor(model => model.NumberOfDogovor)
                        <td> @Model.FileList[i].ToString() </td>
                        <td> @Html.ActionLink("Сохранить", "DownloadOtchet", new { ImageName = Model.FileList[i].ToString(), id = Model.NumberOfDogovor }) </td>
                    </tr>
                }
            </table>
        </p>
        @Html.ActionLink("Назад", "SSets", "Dogovora")
    </div>
</div>

AdvertizingAgency1/Views/Razrabotki/EmptyFiles.cshtml
@{
    Layout = null;
      @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.8.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Файлов нет</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="contentformEdit">
       
        <div class="formEditOrCreate">
            <h2 style="margin-left: 100px;margin-top: 100px">К сожалению файлы по данному договору ещё не загружены!</h2>
            @Html.ActionLink("Назад", "SLookMaket", "Dogovora")
        </div>
    </div>
    <div>
       
    </div>
    </body>
</html>

AdvertizingAgency1/Views/Razrabotki/EmptyFilesOriginal.cshtml
@{
    Layout = null;
      @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.8.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Файлов нет</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="contentformEdit">

        <div class="formEditOrCreate">
            <h2 style="margin-left: 100px;margin-top: 100px">К сожалению файлы по данному договору ещё не загружены!</h2>
            @Html.ActionLink("Назад", "SInMasters", "Dogovora")
        </div>
    </div>
    <div>

    </div>
</body>
</html>

AdvertizingAgency1/Views/Razrabotki/EmptyFilesOtchet.cshtml
@{
    Layout = null;
      @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.8.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Файлов нет</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="contentformEdit">

        <div class="formEditOrCreate">
            <h2 style="margin-left: 100px;margin-top: 100px">К сожалению файлы по данному договору ещё не загружены!</h2>
            @Html.ActionLink("Назад", "SSets", "Dogovora")
        </div>
    </div>
    <div>

    </div>
</body>
</html>