AdvertizingAgency1/Models/ClientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DAL;

namespace AdvertizingAgency1.Models
{
    public class ClientsViewModel
    {
        public IEnumerable<Клиенты> client { get; set; }
        public IEnumerable<Контактное_лицо> contactnoeLico { get; set; }

        public PagingInfoViewModel PagingInfo { get; set; }
    }
}

AdvertizingAgency1/Models/EditClientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DAL;

namespace AdvertizingAgency1.Models
{
    public class EditClientsViewModel
    {
        public Клиенты client { get; set; }
        public Контактное_лицо contact { get; set; }
    }
}

AdvertizingAgency1/Controllers/ClientsController.cs
using System.Linq;
using System.Web.Mvc;
using AdvertizingAgency1.Models;
using BusinessLogic;
using DAL;

namespace AdvertizingAgency1.Controllers
{
    public class ClientsController : Controller
    {
        private DataManager dataManager;
        public int PageSize = 15;

        public ClientsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
         [Authorize(Roles = "admin,maneger,bookkeeper,designer,master,installer")]
        public ActionResult Index(int page = 1)
        {
            ClientsViewModel allclients = new ClientsViewModel();
            allclients.client = dataManager.ClientsRepository.GetClients().Skip((page-1)*PageSize).Take(PageSize);
            allclients.contactnoeLico = dataManager.ContaktnoeLicoRepository.GetContactnoeLico();
            allclients.PagingInfo = new PagingInfoViewModel
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = dataManager.ClientsRepository.GetClients().Where(x => x.Статус != "новый").Count()
            };
            return View(allclients);
        }
         [Authorize(Roles = "admin,maneger")]
        public ActionResult NewClients(int page=1)
        {
            ClientsViewModel allclients = new ClientsViewModel();
            allclients.client = dataManager.ClientsRepository.GetClients();
            allclients.contactnoeLico = dataManager.ContaktnoeLicoRepository.GetContactnoeLico();
            allclients.PagingInfo = new PagingInfoViewModel
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = dataManager.ClientsRepository.GetClients().Where(x => x.Статус == "новый").Count()
            };
            return View(allclients);
        }

          [Authorize(Roles = "admin,maneger")]
        [HttpGet]
        public ActionResult EditClient(int id)
        {
              CreateClientForDogovorViewModel model = new CreateClientForDogovorViewModel();
              Клиенты client = dataManager.ClientsRepository.GetClientsById(id);
              Контактное_лицо contact = dataManager.ContaktnoeLicoRepository.GetContactnoeLicoById(id);
              model.clientId = id;
              model.clientName = client.Наименование;
              model.clientUNP = (int)client.УНП;
              model.clientAdres = client.Адрес;
              model.clientEmail = contact.Email;
              model.clientFio = contact.ФИО;
              model.clientPhone = contact.Телефон;
              model.clientSkype = contact.Skype;
              model.clientPogelanie = contact.Пожелания;
         return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin,maneger")]
          public ActionResult EditClient(CreateClientForDogovorViewModel model)
        {
            if (ModelState.IsValid)
            {
                dataManager.ClientsRepository.CreateClient(model.clientId,model.clientName,model.clientUNP,model.clientAdres,dataManager.ClientsRepository.GetClientsById(model.clientId).Статус);
                int ID =
                    dataManager.ClientsRepository.GetClients().OrderBy(x => x.Код_клиента).LastOrDefault().Код_клиента;
                dataManager.ContaktnoeLicoRepository.CreateContactnoeLico(ID,model.clientFio,model.clientPhone,model.clientEmail,model.clientSkype,model.clientPogelanie);
              
                return RedirectToAction("Index");
            }
            return View(model);
       }
          [Authorize(Roles = "admin,maneger")]
        [HttpGet]
        public ActionResult DeleteClients(int id)
        {
            dataManager.ClientsRepository.DeleteClient(dataManager.ClientsRepository.GetClientsById(id));
            return RedirectToAction("Index");
        }

    }
}

AdvertizingAgency1/Views/Clients/EditClient.cshtml
@using DAL;
@using AdvertizingAgency1.Models
@model CreateClientForDogovorViewModel
@{
    Layout = null;
      @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.8.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
}
<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
<title>"Изменение клиента"</title>
<div class="contentformEdit">

    <h2>Изменить данные клиента:</h2>

    <div class="formEditOrCreate">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Клиент</legend>

                @Html.HiddenFor(model => model.clientId)
             
             <div class="editor-label">
                    @Html.Label("Наименование")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientName)
                    @Html.ValidationMessageFor(model => model.clientName)
                </div>

                <div class="editor-label">
                    @Html.Label("УНП")
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.clientUNP)
                    @Html.ValidationMessageFor(model => model.clientUNP)
                </div>
                <div class="editor-label">
                    @Html.Label("ФИО контактного лица")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientFio)
                    @Html.ValidationMessageFor(model => model.clientFio)
                </div>
                <div class="editor-label">
                    @Html.Label("Номер телефона")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientPhone)
                    @Html.ValidationMessageFor(model => model.clientPhone)
                </div>
                <div class="editor-label">
                    @Html.Label("Email")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientEmail)
                    @Html.ValidationMessageFor(model => model.clientEmail)
                </div>
                <div class="editor-label">
                    @Html.Label("Skype")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientSkype)
                    @Html.ValidationMessageFor(model => model.clientSkype)
                </div>
                <div class="editor-label">
                    @Html.Label("Адрес")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.clientAdres)
                    @Html.ValidationMessageFor(model => model.clientAdres)
                </div>

                <div class="editor-label">
                    @Html.Label("Пожелания")
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.clientPogelanie)
                    @Html.ValidationMessageFor(model => model.clientPogelanie)
                </div>

                <p>
                    <input type="submit" value="Сохранить изменения" />
                </p>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Назад", "Index")
        </div>
    </div>
</div>

AdvertizingAgency1/Views/Clients/Index.cshtml
@using DAL;
@using AdvertizingAgency1.Models
@model ClientsViewModel
@{
    ViewBag.Title = "Клиенты";
}
<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
<h2>Список всех клиентов</h2>
@*@if (HttpContext.Current.User.IsInRole("admin") || HttpContext.Current.User.IsInRole("maneger"))
{
    <ul class="multimenu">
        <li class="activepage">  @Html.ActionLink("Все клиенты", "Index")</li>
        <li class="nonactivepage"> @Html.ActionLink("Новые клиенты", "NewClients")</li>
    </ul>
}*@
<div>
    <table class="tableAny">
        <tr class="firststringtable">
            <th>Код</th>
            <th>Наименование</th>
            <th>УНП</th>
            <th>Контактное лицо</th>
            <th>Телефон</th>
            <th>Email</th>
            <th>Skype</th>
            <th class="shiroko">Примечание</th>
            <th>Адрес</th>
            <th>Статус</th>
            @if (HttpContext.Current.User.IsInRole("admin") || HttpContext.Current.User.IsInRole("maneger"))
            {
                <th>Удалить</th>
                 <th>Добавить договор</th>
            }
        </tr>
        @foreach (Клиенты client in Model.client)
        {
            if (client.Статус != "новый")
            {
                <tr>
                    <td>@client.Код_клиента</td>
                    @if (HttpContext.Current.User.IsInRole("admin") || HttpContext.Current.User.IsInRole("maneger"))
                    {
                        <td>@Html.ActionLink(@client.Наименование, "EditClient", "Clients", new {id = client.Код_клиента}, null)</td>
                    }
                    else
                    {
                      <td>@client.Наименование</td>
                    }            
                    <td>@client.УНП</td>
                    @foreach (Контактное_лицо contact in Model.contactnoeLico)
                    {
                        if (client.Код_клиента == contact.Код_клиента)
                        {
                            <td>@contact.ФИО</td>
                            <td>@contact.Телефон</td>
                            <td>@contact.Email</td>
                            <td>@contact.Skype</td>
    <td class="shiroko">@contact.Пожелания</td>
                        }
                    }
                    <td>@client.Адрес</td>
                    <td>@client.Статус</td>  
                        @if (HttpContext.Current.User.IsInRole("admin") || HttpContext.Current.User.IsInRole("maneger"))
                        {
                            <td>@Html.ActionLink("Удалить", "DeleteClients", "Clients", new { id = client.Код_клиента }, null)</td>
                            @*<td>@Html.ActionLink("Новый договор", "CreateDogovor", "Dogovora", new { id = client.Код_клиента }, null)</td>*@
                              <td>@Html.ActionLink("Новый договор", "Index", "Zakaz", new { id = client.Код_клиента,newdogovor = true }, null)</td>
                        } 
                </tr>
            }
        }
    </table>
</div>
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new { page = x }))
</div> 





    

AdvertizingAgency1/Views/Clients/NewClients.cshtml
@using DAL;
@using AdvertizingAgency1.Models
@model ClientsViewModel
@{
    ViewBag.Title = "Клиенты";
}

<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
<h2>Список клиентов оставивших заявки:</h2>
@*<ul class="multimenu">
    <li class="nonactivepage">  @Html.ActionLink("Все клиенты  ", "Index")</li>
    <li class="activepage"> @Html.ActionLink("Новые клиенты", "NewClients")</li>
</ul>*@
<div>
    <table class="tableAny">
        <tr class="firststringtable">
            <th>ФИО</th>
            <th>Телефон</th>
            <th>Email</th>
            <th>Skype</th>
            <th>Примечание</th>
            <th>Удалить</th>
            <th>Заключить договор</th>
        </tr>
        @foreach (Клиенты client in Model.client)
        {
            if (client.Статус == "новый")
            {
                <tr>
                    @foreach (Контактное_лицо contact in Model.contactnoeLico)
                    {
                        if (client.Код_клиента == contact.Код_клиента)
                        {
                            <td>@contact.ФИО</td>
                            <td>@contact.Телефон</td>
                            <td>@contact.Email</td>
                            <td>@contact.Skype</td>
                            <td>@contact.Пожелания</td>
                            <td>@Html.ActionLink("Удалить", "DeleteClients", "Clients", new { id = client.Код_клиента }, null)</td>
                            <td>@Html.ActionLink("Новый договор", "UpdateClients", "Dogovora", new { id = client.Код_клиента }, null)</td>
                        }
                    }
                </tr>
            }
        }
    </table>
</div>
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("NewClients", new { page = x }))
</div> 